version: '1.0.{build}'

environment:
  matrix:
    - RUBY_VERSION: 193
      # AppVeyor does not have a 64-bit Ruby 1.9.3
    - RUBY_VERSION: 23
    - RUBY_VERSION: 23-x64

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake report_builder:test_everything
